---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-flexible-nodes
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test-flexible-nodes
  template:
    metadata:
      labels:
        app: nginx-test-flexible-nodes
    spec:
      containers:
      - image: nginx
        name: nginx-test-flexible-nodes
        resources: 
         limits:
           cpu: "20"
         requests:
           cpu: "10"
