apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-certificate
spec:
  secretName: app-tls-secret
  ipAddresses:
    - 10.1.2.3
  issuerRef:
    name: selfsigned-certificate
    kind: ClusterIssuer
