---
kind: Service
apiVersion: v1
metadata:
 labels:
   app: supermario
 name: supermarioservice
 namespace: default
spec:
 ports:
   - port: 80
     targetPort: 8080
 selector:
   app: supermario
   
