---
kind: Service
#kubectl create deployment supermario  --image=pengbai/docker-supermario
#kubectl  scale deployment/supermario --replicas=2
#kubectl expose deployment supermario --name=supermarioloadbalancer --port=80 --target-port=8080 --type=LoadBalancer
#kubectl create secret tls certtls --cert=crt --key=key
apiVersion: v1
metadata:
 labels:
   app: supermario
 name: supermarioservice
 namespace: default
spec:
 ports:
   - port: 80
     targetPort: 8080
 selector:
   app: supermario



---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: ingressmario
 namespace: default
 annotations:
   cert-manager.io/cluster-issuer: test-production-cert
spec:
 rules:
 - host: 11111111111
   http:
     paths:
     - pathType: Prefix
       path: "/"
       backend:
         service:
           name: supermarioloadbalancer
           port:
             number: 80
 tls:
 - hosts:
   - 11111111111
   secretName: 11111111111




#kubectl  scale deployment/supermario --replicas=2
#kubectl expose deployment supermario --name=supermarioloadbalancer --port=80 --target-port=8080 --type=LoadBalancer
#kubectl expose deployment supermario --name=supermarioloadbalancer --port=80 --target-port=8080 --type=NodePort
#kubectl  expose deployment/supermario --name=supermario --port=8080
#            spec:
#              hostNetwork: true
#              nodeName: {master_node_hostname}
#              containers:
#                - name: kubernetes-dashboard
#                  image: kubernetesui/dashboard:v2.5.0
#                  imagePullPolicy: Always
#                  ports:
#                   - containerPort: 8443
#                      protocol: TCP
#                      hostPort: 8443

